#! /bin/bash
#$ -N QC-dev
#$ -S /bin/bash
#$ -q bigmem-r8.q,research-r8.q,researchlong-r8.q,researchshort-r8.q #Operational eventually?
#$ -pe shmem-1 1
#$ -l h_rss=20G,mem_free=20G,h_data=20G
#$ -l h_rt=4:00:00
#$ -v STORE,SNAPPY
#$ -M geche8548@met.no
#$ -m abe
#$ -P dsa
#$ -o /home/geche8548/snap-runs/QC-dev/test-job-runs
#$ -e /home/geche8548/snap-runs/QC-dev/test-job-runs
#$ -t 2 #1-17

umask 0002
# ~4 mio particles, use 2 (hyper-) threads
export OMP_NUM_THREADS=2
export OMP_THREAD_LIMIT=2
export OPENBLAS_NUM_THREADS=1
export MAGICK_THREAD_LIMIT=1

module load --silent /modules/MET/rhel8/user-modules/fou-modules/SnapPy/"$SNAPPY"

set -x

LOGFILE=/home/geche8548/snap-runs/QC-dev/test-job-runs/test-job_$(date -d "today" +"%Y%m%dT%H%M").log
LUSTRE=/lustre/storeB/project/fou/kl/cerad/Projects/QC/ModelRuns/

# if [ -d "v$SNAPPY" ];
# then
#     echo "Directory v$SNAPPY already exists. Delete old directory to run again or try different version." >> "$LOGFILE"
#     exit "Directory v$SNAPPY already exists."
# else
#     echo "Creating version directory" >> "$LOGFILE"
#     mkdir "v$SNAPPY"
#     VDIR=v$SNAPPY
# fi
VDIR=v$SNAPPY

# if [ $SGE_TASK_ID -eq 1 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir RinghalsRainyMeps
#     echo "start work RINGHALS RAINY MEPS" >> "$LOGFILE"
#     cd RinghalsRainyMeps
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsRainyMeps.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 2 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir RinghalsRainyEC 
#     echo "start work RINGHALS RAINY EC" >> "$LOGFILE"
#     cd RinghalsRainyEC
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsRainyEC.input
#     snapAddToa snap.nc
if [ $SGE_TASK_ID -eq 2 ]; then
    cd $LUSTRE/$VDIR
    mkdir RinghalsRainyEC-test 
    echo "start work RINGHALS RAINY EC" >> "$LOGFILE"
    cd RinghalsRainyEC-test
    bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsRainyEC_test.input
    snapAddToa snap.nc
fi
# elif [ $SGE_TASK_ID -eq 3 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir RinghalsRainyICON
#     echo "start work RINGHALS RAINY ICON" >> "$LOGFILE"
#     cd RinghalsRainyICON
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsRainyICON.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 4 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir RinghalsDryMeps
#     cho "start work RINGHALS DRY MEPS" >> "$LOGFILE"
#     cd RinghalsDryMeps
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsDryMeps.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 5 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir RinghalsDryEC
#     echo "start work RINGHALS DRY EC" >> "$LOGFILE"
#     cd RinghalsDryEC
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsDryEC.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 6 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir RinghalsDryICON
#     echo "start work RINGHALS DRY EC" >> "$LOGFILE"
#     cd RinghalsDryICON
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsDryICON.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 7 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir backTrackEC
#     echo "start work BackTrack EC" >> "$LOGFILE"
#     cd backTrackEC
#     bsnap_naccident $HOME/snap/utils/qcTesting/input/backTrackEC.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 8 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir backTrackMEPS
#     echo "start work BackTrack MEPS" >> "$LOGFILE"
#     cd backTrackMEPS
#     bsnap_naccident $HOME/snap/utils/qcTesting/input/backTrackMEPS.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 9 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir backTrackICON
#     echo "start work BackTrack ICON" >> "$LOGFILE"
#     cd backTrackICON
#     bsnap_naccident $HOME/snap/utils/qcTesting/input/backTrackICON.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 10 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir pseudoDryEC
#     echo "start work Pseudo EC" >> "$LOGFILE"
#     cd pseudoDryEC
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsPseudoDryEC.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 11 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir nuclideDryEC
#     echo "start work nuclide EC" >> "$LOGFILE"
#     cd nuclideDryEC
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsNuclideDryEC.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 12 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir pseudoDryMEPS
#     echo "start work Pseudo MEPS" >> "$LOGFILE"
#     cd pseudoDryMEPS
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsPseudoDryMEPS.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 13 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir nuclideDryMEPS
#     echo "start work Nuclide MEPS" >> "$LOGFILE"
#     cd nuclideDryMEPS
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsNuclideDryMEPS.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 14 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir pseudoDryMEPS
#     echo "start work Pseudo MEPS" >> "$LOGFILE"
#     cd pseudoDryMEPS
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsPseudoDryMEPS.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 15 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir nuclideDryMEPS
#     echo "start work Nuclide MEPS" >> "$LOGFILE"
#     cd nuclideDryMEPS
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsNuclideDryMEPS.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 16 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir pseudoDryICON
#     echo "start work Pseudo MEPS" >> "$LOGFILE"
#     cd pseudoDryICON
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsPseudoDryICON.input
#     snapAddToa snap.nc

# elif [ $SGE_TASK_ID -eq 17 ]; then
#     cd $LUSTRE/$VDIR
#     mkdir nuclideDryICON
#     echo "start work Nuclide MEPS" >> "$LOGFILE"
#     cd nuclideDryICON
#     # bsnap_naccident $HOME/snap/utils/qcTesting/input/RinghalsNuclideDryICON.input
#     snapAddToa snap.nc
# fi
# cd $LUSTRE/$VDIR
# mkdir ChernobylMEPS
# echo "start work ChernobylMEPS MEPS" >> "$LOGFILE"
# cd ChernobylMEPS
#export OMP_NUM_THREADS=4
# bsnap_naccident $HOME/snap/utils/qcTesting/input/ChernobylMEPS.input
