#!/bin/ksh
#
#  Usage: /bin/ksh get_cycle $ROOTDIR/odb/lib/version.c
#
#  Extracts CYCLE-string CYXXRY.ZZZ from odb/lib/version.c
#

set -eu

CYCLE=CYXXRY.ZZZ

if [[ $# -ge 1 ]] ; then
  file=$1
  if [[ -r $file ]] ; then
    major=$(perl -ne 'print $1 if (m/^#\s*define\s+VERSION_MAJOR\s+(\S+)/)' < $file 2>/dev/null)
    minor=$(perl -ne 'print $1 if (m/^#\s*define\s+VERSION_MINOR\s+(\S+)/)' < $file 2>/dev/null)
    CYCLE="CY${major}R${minor}"
  fi
fi

echo $CYCLE
