#! /usr/bin/env python3
#
# SNAP: Servere Nuclear Accident Programme
# Copyright (C) 1992-2017   Norwegian Meteorological Institute
# 
# This file is part of SNAP. SNAP is free software: you can 
# redistribute it and/or modify it under the terms of the 
# GNU General Public License as published by the 
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
'''Create *ARGOS2SNAP.zip and *ARGOS2TRAJ.zip files with current dates'''

import datetime
import zipfile


rimsterm = '''<CBRN_Sourceterm Version="23">
<Header><Author>ARGOS application: 9.3.8.0  - User: msolberg</Author>
<SourceDoc/>
<Place>
<Location Longitude="-1.18083333333333" Latitude="54.6344444444444"/></Place>
<Comments><Comment>Created on: {date}T07:24:09Z</Comment><Comment>Generated by ARGOS from an incident</Comment><Comment>based on a release from a Radiological Source</Comment></Comments></Header><SourceDomain>N</SourceDomain>
<ItemsTot Number="1">
<Item ItemName="Cs-137" ItemNum="169"/></ItemsTot><TimeOfInitialRelease>{date}T07:23:00Z</TimeOfInitialRelease>
<Source SourceId="00">
<TimeIndependent>
<SizeBins Number="2">
<SizeBin BinId="0" ParticleDiameter="0" ParticleDensity="0"/>
<SizeBin BinId="1" ParticleDiameter="0.000001" ParticleDensity="1000"/></SizeBins><StartTime>{date}T07:23:00Z</StartTime>
<StartPosition Longitude="-1.18083" Latitude="54.6344" HeightAboveGround="100" HeightAboveGroundMax="0" Datum="WGS84"/>
<SourceItems Number="1">
<SourceItem ItemName="Cs-137" Parameters="Lookup"/></SourceItems></TimeIndependent>
<TimeDependent>
<ReleaseInterval>
<SourceTime EndTime="P2DT12H"/>
<SourceStrength ItemName="Cs-137" Unit="Bq/s">
<BinStrength BinId="1" Value="1e+11"/></SourceStrength>
<SourcePosition Longitude="-1.18083" Latitude="54.6344" HeightAboveGround="100" HeightAboveGroundMax="0" Datum="WGS84"/>
<SourcePuffSigmaYZ Unit="m" SigmaY="1" SigmaZ="1"/>
<SourceHeat Unit="W" Value="0"/></ReleaseInterval></TimeDependent></Source></CBRN_Sourceterm>'''

rimsterm_back = '''<?xml version="1.0" encoding="Windows-1252"?>
<CBRN_Sourceterm Version="23">
<Header><Author>ARGOS application: 9.4.9.0  - User: JanErik</Author>
<SourceDoc/>
<Place>
<Location Longitude="12.1" Latitude="57.25"/></Place>
<Comments><Comment>Created on: {date}T13:55:00Z</Comment><Comment>Generated by ARGOS from an incident</Comment><Comment>based on a release from a Radiological Source</Comment></Comments></Header><SourceDomain>N</SourceDomain>
<ItemsTot Number="2">
<Item ItemName="I -131" ItemNum="148"/>
<Item ItemName="Cs-137" ItemNum="169"/></ItemsTot><TimeOfInitialRelease>{date}T13:54:00Z</TimeOfInitialRelease>
<Source SourceId="00">
<TimeIndependent>
<SizeBins Number="1">
<SizeBin BinId="2" ParticleDiameter="0.000001" ParticleDensity="1000"/></SizeBins><StartTime>{date}T13:54:00Z</StartTime>
<StartPosition Longitude="12.1" Latitude="57.25" HeightAboveGround="0" HeightAboveGroundMax="0" Datum="WGS84"/>
<SourceItems Number="2">
<SourceItem ItemName="I -131" Parameters="Lookup"/>
<SourceItem ItemName="Cs-137" Parameters="Lookup"/></SourceItems></TimeIndependent>
<TimeDependent>
<ReleaseInterval>
<SourceTime EndTime="P1D"/>
<SourceStrength ItemName="I -131" Unit="Bq/s">
<BinStrength BinId="2" Value="1736.11111111111"/></SourceStrength>
<SourceStrength ItemName="Cs-137" Unit="Bq/s">
<BinStrength BinId="2" Value="11574074.0266667"/></SourceStrength>
<SourcePosition Longitude="12.1" Latitude="57.25" HeightAboveGround="0" HeightAboveGroundMax="0" Datum="WGS84"/>
<SourcePuffSigmaYZ Unit="m" SigmaY="10" SigmaZ="10"/>
<SourceHeat Unit="W" Value="0"/></ReleaseInterval></TimeDependent></Source></CBRN_Sourceterm>
'''
request_back = '''<?xml version="1.0" encoding="Windows-1252"?>
<Request>
<RunLength>-24</RunLength>
<OutputTimestep>3</OutputTimestep>
<OutputFormat>NetCDF</OutputFormat>
</Request>
'''

traj_input = '''BROKDORF_(KBR)       Source name
 53.851              Latitude (dec.deg.)
  9.346              Longitude (dec.deg.)
{date}1029         Start (UTC)
forward             Mode (forward / backward)
60                   Simulation duration (h)
3                    Number of parcels
  50.0               First parcel (metres above surface)
 100.0               Second parcel (metres above surface)
 500.0               Third parcel (metres above surface)
'''

traj_back = '''backward2            Source name
 69.387              Latitude (dec.deg.)
 23.760              Longitude (dec.deg.)
{date}0703         Start (UTC)
backward             Mode (forward / backward)
48                   Simulation duration (h)
3                    Number of parcels
  30.0               First parcel (metres above surface)
 500.0               Second parcel (metres above surface)
1500.0               Third parcel (metres above surface)
'''

today = datetime.datetime.now()
tomorrow = today + datetime.timedelta(days=1)

with zipfile.ZipFile('Hartlepool-777_ARGOS2SNAP.zip', 'w') as zh:
    zh.writestr('Hartlepool-777_Rimsterm.xml', rimsterm.format(date=today.strftime('%Y-%m-%d')))

with zipfile.ZipFile('TestBackModeling_ARGOS2SNAP.zip', 'w') as zh:
    zh.writestr('TestBackModeling_Rimsterm.xml', rimsterm_back.format(date=today.strftime('%Y-%m-%d')))
    zh.writestr('TestBackModeling_SNAP_request.xml', request_back)
    
with zipfile.ZipFile('Brokdorf_test_2_ARGOS2TRAJ.zip', 'w') as zh:
    zh.writestr('Brokdorf_test_2_TRAJ_input', traj_input.format(date=today.strftime('%Y%m%d')))

with zipfile.ZipFile('backward2_ARGOS2TRAJ.zip', 'w') as zh:
    zh.writestr('backward2_TRAJ_input', traj_back.format(date=today.strftime('%Y%m%d')))
