#! /usr/bin/env python

import netCDF4
import argparse
import numpy

parser = argparse.ArgumentParser()
parser.add_argument("snapNc", help="snap.nc file to be changed")
args = parser.parse_args()


with netCDF4.Dataset(args.snapNc, "a") as nc:
    if ('time_of_arrival' in nc.variables):
        exit(0)
    times = netCDF4.num2date(nc.variables['time'][:],units=nc.variables['time'].units)
    timeMax = int((times[-1] - times[0]).total_seconds() / (60*60))
    timeDelta = int((times[1] - times[0]).total_seconds() / (60*60))
    data = 0
    exampleVar = ""
    for v in nc.variables.keys():
        if (v[-18:] == "_acc_concentration"):
            exampleVar = v
            data += nc.variables[v][:]
    arrived = numpy.where(data >= 1)
    flying = numpy.where(data < 1)
    data[arrived] = 0
    data[flying] = timeDelta # timeDelta hourly data
    toa = numpy.sum(data, axis=0)
    toa[numpy.where(toa > timeMax)] = -999
    # snap output start at first timeDelta, not 0, so 0 means 0 - 3h
    # make sure that timestamp means 'within this time', e.g. 0 -> 3
    # use slightly less, so that diana is satisfied [0,3[
    toa[numpy.where(toa != -999)] += (float(timeDelta) - 0.01)

    toaVar = nc.createVariable('time_of_arrival', 'f', nc.variables[exampleVar].dimensions, zlib=True, fill_value=-999)
    toaVar.units = 'hours'
    toaVar.grid_mapping = nc.variables[exampleVar].grid_mapping
    toaVar[0,:] = toa

    # add also total depositions
    for v in nc.variables.keys():
        if (v[-19:] == "_acc_wet_deposition"):
            comp = v[:-19]
#            print(comp)
            total = nc.variables[v][:] + nc.variables["{}_acc_dry_deposition".format(comp)][:]
            totalVar = nc.createVariable('{}_acc_total_deposition'.format(comp), 'f', nc.variables[v].dimensions, zlib=True)
            totalVar.units = nc.variables[v].units
            totalVar.grid_mapping =  nc.variables[v].grid_mapping
            totalVar[:] = total
