SUBROUTINE DR_HOOK_PRT(KUNIT, CDSTR)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT(IN) :: KUNIT
CHARACTER(LEN=*), INTENT(IN) :: CDSTR

IF (KUNIT < 0) THEN
  WRITE(*,'(A)') CDSTR
ELSE
  WRITE(KUNIT,'(A)') CDSTR
ENDIF

END SUBROUTINE DR_HOOK_PRT
