c-----------------------------------------------------------------------
c snapdebug.inc
c
c..include file  -  common for debugging.....
c
c..idebug - 0 = debug off
c	    1 = debug on, note that mrfturbo/mrfelt only
c		          prints to standard out (not the log file)
c
      integer idebug
c
      common/debugcom/idebug
c
c-----------------------------------------------------------------------
